@StudyNotesApi_HostAddress = http://localhost:5080

GET {{StudyNotesApi_HostAddress}}/
Accept: application/json

###

GET {{StudyNotesApi_HostAddress}}/api
Accept: application/json

###

GET {{StudyNotesApi_HostAddress}}/api/health
Accept: application/json

###

POST {{StudyNotesApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Victor",
  "email": "victor@email.com",
  "password": "123456"
}

###

POST {{StudyNotesApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "victor@email.com",
  "password": "123456"
}

###

@AuthToken = replace-with-bearer-token

GET {{StudyNotesApi_HostAddress}}/api/categories
Authorization: Bearer {{AuthToken}}
Accept: application/json

###

POST {{StudyNotesApi_HostAddress}}/api/categories
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "name": "Backend",
  "color": "#2563EB"
}

###
